name: Backend CI

on:
  push: # Trigger this workflow on every push to the repository
    branches:
      - main # Run when changes are pushed to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Run this job on a fresh Ubuntu Linux server provided by GitHub

    steps:
      - name: Checkout code # Step 1: Get your code from GitHub
        uses: actions/checkout@v4

      - name: Set up Node.js # Step 2: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use Node.js version 18

      - name: Install dependencies # Step 3: Install project packages (npm install)
        run: npm install

      - name: Run tests # Step 4: Run any automated tests (we don't have tests yet, but this is a placeholder)
        run: echo "No backend tests configured yet, but CI will run here."

      # This project doesn't have a deployable "build" artifact like frontend,
      # but we could conceptually archive the code if needed for later stages.
      # - name: Archive backend code
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: backend-code
      #     path: .